/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uieditor;

import javax.swing.JFrame;

/**
 *
 * @author Anna
 */
public class EndScreenUI extends javax.swing.JFrame {
    /**
     * Creates new form EndScreenUI
     */
    public EndScreenUI() {
        initComponents();
    }

    public void displayLoss()
    {
        WLLabel.setText("Oh, no!");
        DescLabel.setText("You were unable to defeat the overlords! Get back up and fight!");
    }
    public void displayWin()
    {
        WLLabel.setText("Congratulations");
        DescLabel.setText("You have successfully overthrown the furniture overlords and liberated the store!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WLLabel = new javax.swing.JLabel();
        DescLabel = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WLLabel.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        WLLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WLLabel.setText("Congratulations!");

        DescLabel.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        DescLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescLabel.setText("You have successfully overthrown the furniture overlords and liberated the store!");

        ExitButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        ExitButton.setText("Exit to Menu");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(WLLabel)
                    .addComponent(DescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(WLLabel)
                .addGap(70, 70, 70)
                .addComponent(DescLabel)
                .addGap(18, 18, 18)
                .addComponent(ExitButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.setVisible(false);
        MenuUI mui = new MenuUI();
        mui.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        mui.setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel WLLabel;
    // End of variables declaration//GEN-END:variables
}
